### ISSUE TITLE
Improve testing time by skipping slp discovery

### ISSUE THREAD

**Issue by cstockloew** [universAAL/itests#2]
During itests, the discovery of AAL spaces is not needed (not even desired for single-node execution). However, the SLP discovery connector searches via IP multicast several times for an AAL Space and has a Thread.sleep between polls. Default value is "3000,2000,1500,1000,750,500" = 8,75 seconds (yes, I know it's not _that_ much).

Some artifacts override this value (e.g. bus.model - ArtifactIT) by calling
`setRunArguments("net.slp.multicastTimeouts", "500,750");` 
which corresponds to 1,25 s. This value seems to be copied to many other ArtifactIT classes, i.e. in mw and samples.

Maybe there should be a small value set as default directly in org.universAAL.itests.IntegrationTest. The values in all ArtifactIT's can then be removed.

BTW: this can also be used in run configs by adding 
`-Dnet.slp.multicastTimeouts=10,10`
to the VM arguments to speed up starting time.

**Comment by amedranogil** [comment]
One modification we introduced some time ago was to ensure the discovery and peering to be bounded to localhost. This way the discovery should be fast.
I thought that I also touched some of the timeouts in the [config](https://github.com/universAAL/itests/blob/master/itests-conf/src/main/resources/uAALmw.properties).
In any case these need to be reviewed ([according to the latest info I got](https://github.com/universAAL/platform/wiki/RD-Middleware#Run_universAAL_middleware_without_network)).

**Comment by amedranogil** [comment]
test if the modifications work better now.

**Comment by cstockloew** [comment]
no change, seems like the props are ignored.

**Comment by michelegirolami** [comment]
just to double check your configuration... have you set the role of your universAAL instance as COORDINATOR?
BTW, as @amedranogil  posted, you can configure you instance as local so that to avoid multicasting outside the local network.

**Comment by amedranogil** [comment]
this is odd, because I know the properties are passed as system properties.
ensure you build the whole itest suite (twice) before testing, as the modules are embedded into the main itest (if you build only the base modules it will not be used).

**Comment by amedranogil** [comment]
@michelegirolami  Yes, see the properties here: https://github.com/universAAL/itests/blob/master/itests-conf/src/main/resources/uAALmw.properties

**Comment by cstockloew** [comment]
Interesting.
- I added a sysout to itests (in IntegrationTestConsts.getuAALMWProperties) to print out all props. And when I execute an itest, they will be correctly shown.
- I modfied locally an IT, in my case I chose mw.bus.model.osgi:
-- removed the line " setRunArguments("net.slp.multicastTimeouts", "500,750");" 
-- added a sysout of all system props to testComposite (so that it will be printed during/at the end of the tests)
--> The properties are not there

In an older javadoc (not the version we use, but ok) at http://grepcode.com/file/repo1.maven.org/maven2/org.apache.felix/org.apache.felix.framework/4.0.3/org/apache/felix/framework/Felix.java#Felix.%3Cinit%3E%28java.util.Map%29
(scroll up)
I found this: "Configuration properties are used **internally by the framework** to alter its default behavior."

Conclusion:
- the properties in uAALmw.properties are NOT set as system properties, they are considered by felix, but not by the bundles that run in felix
- only when you call setRunArguments in an ArtifactIT, it will be set as system prop

**Comment by amedranogil** [comment]
in the end I had to put the properties directly to system properties... IDK why the framework for adding system properties to the felix framework before starting it did not work...

I've checked, at least it is now getting the properties from the uAALmw.properties

**Comment by cstockloew** [comment]
It works. I just deployed itests and mw. thx
